const triviaTopics = [
  {
    id: "Herons",
    title: "Herons",
    topic: "Nature",
    category: "Animals",
    date: "July 9, 2026",
    image: "/projects/daily-trivia/images/Heron.jpg",
    youtube: "https://www.youtube.com/watch?v=nIjT201Hs_U",
    information: [
        "---",
        "🦢 Meet the Graceful Heron!",
        "---",
        " Herons are elegant wading birds found on every continent except Antarctica. They are most often seen standing quietly along the edges of lakes, rivers, marshes, and coastlines, patiently waiting for their next meal. Their long legs allow them to walk through shallow water, while their long necks and sharp, pointed beaks make them excellent hunters.",
        "Herons mainly eat fish, but they also enjoy frogs, insects, snakes, small mammals, and even crustaceans. Instead of chasing their prey, they usually stand perfectly still until the right moment, then strike with lightning-fast speed using their powerful beak. This patient hunting style helps them catch prey with remarkable accuracy.",
        "Although herons often appear solitary while feeding, many species gather together in large nesting colonies called rookeries. They build nests high in trees or shrubs near water, where both parents help care for their chicks.",
        "One of the most recognizable species is the Great Blue Heron, which can stand over four feet tall and have a wingspan reaching nearly seven feet. Despite their large size, herons are graceful fliers. They fold their necks into an 'S' shape during flight, unlike cranes, which fly with their necks stretched straight out.",
        "Herons play an important role in wetland ecosystems by helping control fish, insect, and amphibian populations. Because they rely on healthy wetlands to survive, seeing herons is often a sign that the local environment is thriving.",
        "---",
        "🦢 Fun Heron Trivia",
        "---",
        " A group of nesting herons is called a rookery.",
        "Herons can stand completely still for several minutes while hunting.",
        "The Great Blue Heron has a wingspan of up to 7 feet (2.1 meters).",
        "Herons fly with their neck folded into an S-shape.",
        "Some herons use bait, such as feathers or insects, to attract fish.",
        "Herons have excellent eyesight that helps them hunt during both the day and twilight.",
        "There are more than 60 species of herons found around the world.",
    ],
    questions: [
        "Why do herons have long legs?",
        "What is the main food that herons eat?",
        "How do herons usually catch their prey?",
        "True or False: Herons fly with their necks stretched straight out.",
        "What is a rookery?"
    ],
    answers: [
        "Their long legs help them walk through shallow water while hunting.",
        "Fish are their primary food, although they also eat frogs, insects, snakes, and other small animals.",
        "They stand very still and quickly strike their prey with their sharp beak.",
        "False. Herons fly with their necks folded into an S-shape.",
        "A rookery is a large nesting colony where many herons build their nests together.",
    ] 
  },
  {
    id: "Andean Mountain Cat",
    title: "🐈 Andean Mountain Cat",
    topic: "Nature",
    category: "Animal",
    date: "Date: July 11, 2026",
    image: "https://greatergood.org/hs-fs/hubfs/VS-Photograph_20240401_BC_ArgentinaLandPurchase_006_FEATURED_©JuanReppucci.png?width=800&height=420&name=VS-Photograph_20240401_BC_ArgentinaLandPurchase_006_FEATURED_©JuanReppucci.png",
    youtube: "https://youtu.be/JPo1jiLfZ1M?si=UAaoyvoEXcdZqx_G",
    information: [
        "---------------------------------------------------------------------------------------------------------------------",
        "🐈 Meet the Elusive Andean Mountain Cat!",
        "---------------------------------------------------------------------------------------------------------------------",
        "The Andean mountain cat is one of the rarest and most mysterious wild cats on Earth.",
        "It lives high in the Andes Mountains of South America, where the rocky landscape, cold temperatures, and thin mountain air make survival challenging.",
        "Scientists estimate that fewer than 1,400 adult Andean mountain cats remain in the wild, making them one of the world's most endangered wild cat species.",
        "---------------------------------------------------------------------------------------------------------------------",
        "These beautiful cats have thick, silver-gray fur covered with brownish-orange spots and stripes that help them blend into the rocky mountains.",
        "Their long, bushy tails are marked with dark rings and help them maintain balance while climbing steep cliffs.",
        "Adult Andean mountain cats are about the size of a house cat but have much longer tails.",
        "---------------------------------------------------------------------------------------------------------------------",
        "The Andean mountain cat is an expert hunter. Its favorite food is the mountain viscacha, a rabbit-like rodent that lives among rocky cliffs.",
        "The cat also hunts birds and other small mammals. Because prey is scarce in the high mountains, the cats often roam over large territories in search of food.",
        "---------------------------------------------------------------------------------------------------------------------",
        "Very little is known about the Andean mountain cat because it is so shy and difficult to find.",
        "Most sightings come from motion-activated trail cameras placed in remote mountain regions.",
        "Researchers continue studying these elusive cats to better understand their behavior and protect their habitat.",
        "---------------------------------------------------------------------------------------------------------------------",
        "The biggest threats facing the Andean mountain cat are habitat loss, declining prey populations, climate change, and human activity.",
        "Conservation groups across Argentina, Bolivia, Chile, and Peru are working together to protect this remarkable animal and ensure it survives for future generations.",
        "---------------------------------------------------------------------------------------------------------------------",
        "🐾 Fun Andean Mountain Cat Trivia",
        "---------------------------------------------------------------------------------------------------------------------",
        "The Andean mountain cat is considered one of the five rarest wild cats in the world.",
        "Scientists estimate there are fewer than 1,400 adults remaining.",
        "It lives at elevations of 9,800 to over 16,000 feet (3,000 to 5,000 meters).",
        "Its long tail can be nearly 70% as long as its body.",
        "The mountain viscacha is its favorite prey.",
        "Many people, including scientists, have never seen one in the wild.",
        "It is found in only four countries: Argentina, Bolivia, Chile, and Peru."
    ],
    questions: [
        "Where does the Andean mountain cat live?",
        "Why is the Andean mountain cat considered rare?",
        "What animal is its favorite prey?",
        "True or False: The Andean mountain cat is much larger than a typical house cat.",
        "Name one threat facing the Andean mountain cat.",
    ],
    answers: [
        "It lives high in the Andes Mountains of South America.",
        "Fewer than about 1,400 adults remain in the wild, making it one of the world's rarest wild cats.",
        "The mountain viscacha.",
        "False. It is about the size of a house cat but has a much longer, bushier tail.",
        "Possible answers include habitat loss, climate change, declining prey populations, or human activity."
    ] 
  }
];