/**
 * Legacy in-memory topic data used by the printable worksheet page.
 *
 * Saved topics created in the editor follow a separate data flow through
 * localStorage; keeping this distinction explicit avoids confusing seed content
 * with user-created library records.
 *
 * @type {Array<Object>}
 */
const triviaTopics = [
  {
    id: "Herons",
    title: "Herons",
    topic: "Nature",
    category: "Animals",
    date: "July 9, 2026",
    image: "/projects/daily-trivia/images/Heron.jpg",
    youtube: "https://www.youtube.com/watch?v=nIjT201Hs_U",
    information: [
        "---",
        "🦢 Meet the Graceful Heron!",
        "---",
        " Herons are elegant wading birds found on every continent except Antarctica. They are most often seen standing quietly along the edges of lakes, rivers, marshes, and coastlines, patiently waiting for their next meal. Their long legs allow them to walk through shallow water, while their long necks and sharp, pointed beaks make them excellent hunters.",
        "Herons mainly eat fish, but they also enjoy frogs, insects, snakes, small mammals, and even crustaceans. Instead of chasing their prey, they usually stand perfectly still until the right moment, then strike with lightning-fast speed using their powerful beak. This patient hunting style helps them catch prey with remarkable accuracy.",
        "Although herons often appear solitary while feeding, many species gather together in large nesting colonies called rookeries. They build nests high in trees or shrubs near water, where both parents help care for their chicks.",
        "One of the most recognizable species is the Great Blue Heron, which can stand over four feet tall and have a wingspan reaching nearly seven feet. Despite their large size, herons are graceful fliers. They fold their necks into an 'S' shape during flight, unlike cranes, which fly with their necks stretched straight out.",
        "Herons play an important role in wetland ecosystems by helping control fish, insect, and amphibian populations. Because they rely on healthy wetlands to survive, seeing herons is often a sign that the local environment is thriving.",
        "---",
        "🦢 Fun Heron Trivia",
        "---",
        " A group of nesting herons is called a rookery.",
        "Herons can stand completely still for several minutes while hunting.",
        "The Great Blue Heron has a wingspan of up to 7 feet (2.1 meters).",
        "Herons fly with their neck folded into an S-shape.",
        "Some herons use bait, such as feathers or insects, to attract fish.",
        "Herons have excellent eyesight that helps them hunt during both the day and twilight.",
        "There are more than 60 species of herons found around the world.",
    ],
    questions: [
        "Why do herons have long legs?",
        "What is the main food that herons eat?",
        "How do herons usually catch their prey?",
        "True or False: Herons fly with their necks stretched straight out.",
        "What is a rookery?"
    ],
    answers: [
        "Their long legs help them walk through shallow water while hunting.",
        "Fish are their primary food, although they also eat frogs, insects, snakes, and other small animals.",
        "They stand very still and quickly strike their prey with their sharp beak.",
        "False. Herons fly with their necks folded into an S-shape.",
        "A rookery is a large nesting colony where many herons build their nests together.",
    ] 
  },
  {
    id: "Andean Mountain Cat",
    title: "🐈 Andean Mountain Cat",
    topic: "Nature",
    category: "Animal",
    date: "Date: July 11, 2026",
    image: "https://greatergood.org/hs-fs/hubfs/VS-Photograph_20240401_BC_ArgentinaLandPurchase_006_FEATURED_©JuanReppucci.png?width=800&height=420&name=VS-Photograph_20240401_BC_ArgentinaLandPurchase_006_FEATURED_©JuanReppucci.png",
    youtube: "https://youtu.be/JPo1jiLfZ1M?si=UAaoyvoEXcdZqx_G",
    information: [
        "---------------------------------------------------------------------------------------------------------------------",
        "🐈 Meet the Elusive Andean Mountain Cat!",
        "---------------------------------------------------------------------------------------------------------------------",
        "The Andean mountain cat is one of the rarest and most mysterious wild cats on Earth.",
        "It lives high in the Andes Mountains of South America, where the rocky landscape, cold temperatures, and thin mountain air make survival challenging.",
        "Scientists estimate that fewer than 1,400 adult Andean mountain cats remain in the wild, making them one of the world's most endangered wild cat species.",
        "---------------------------------------------------------------------------------------------------------------------",
        "These beautiful cats have thick, silver-gray fur covered with brownish-orange spots and stripes that help them blend into the rocky mountains.",
        "Their long, bushy tails are marked with dark rings and help them maintain balance while climbing steep cliffs.",
        "Adult Andean mountain cats are about the size of a house cat but have much longer tails.",
        "---------------------------------------------------------------------------------------------------------------------",
        "The Andean mountain cat is an expert hunter. Its favorite food is the mountain viscacha, a rabbit-like rodent that lives among rocky cliffs.",
        "The cat also hunts birds and other small mammals. Because prey is scarce in the high mountains, the cats often roam over large territories in search of food.",
        "---------------------------------------------------------------------------------------------------------------------",
        "Very little is known about the Andean mountain cat because it is so shy and difficult to find.",
        "Most sightings come from motion-activated trail cameras placed in remote mountain regions.",
        "Researchers continue studying these elusive cats to better understand their behavior and protect their habitat.",
        "---------------------------------------------------------------------------------------------------------------------",
        "The biggest threats facing the Andean mountain cat are habitat loss, declining prey populations, climate change, and human activity.",
        "Conservation groups across Argentina, Bolivia, Chile, and Peru are working together to protect this remarkable animal and ensure it survives for future generations.",
        "---------------------------------------------------------------------------------------------------------------------",
        "🐾 Fun Andean Mountain Cat Trivia",
        "---------------------------------------------------------------------------------------------------------------------",
        "The Andean mountain cat is considered one of the five rarest wild cats in the world.",
        "Scientists estimate there are fewer than 1,400 adults remaining.",
        "It lives at elevations of 9,800 to over 16,000 feet (3,000 to 5,000 meters).",
        "Its long tail can be nearly 70% as long as its body.",
        "The mountain viscacha is its favorite prey.",
        "Many people, including scientists, have never seen one in the wild.",
        "It is found in only four countries: Argentina, Bolivia, Chile, and Peru."
    ],
    questions: [
        "Where does the Andean mountain cat live?",
        "Why is the Andean mountain cat considered rare?",
        "What animal is its favorite prey?",
        "True or False: The Andean mountain cat is much larger than a typical house cat.",
        "Name one threat facing the Andean mountain cat.",
    ],
    answers: [
        "It lives high in the Andes Mountains of South America.",
        "Fewer than about 1,400 adults remain in the wild, making it one of the world's rarest wild cats.",
        "The mountain viscacha.",
        "False. It is about the size of a house cat but has a much longer, bushier tail.",
        "Possible answers include habitat loss, climate change, declining prey populations, or human activity."
    ] 
  },
  {
    id: "Llamas",
    title: "🦙 Llamas",
    topic: "Nature",
    category: "Animal",
    date: "Date: July 13, 2026",
    image: "/projects/daily-trivia/images/katelyn-warner-unsplash.jpg",
    youtube: "https://youtu.be/AxrslX3YdGs?si=38vxQ_La5iXzebIi",
    information: [
        
        "🦙 Meet the Friendly Llama!",
        "",
        "Llamas are gentle, intelligent animals that have lived alongside people in the Andes Mountains of South America for thousands of years.",
        "They were first domesticated by the Inca civilization and have long been used as pack animals because they can carry supplies across steep mountain trails.",
        "Today, llamas are found on farms and ranches all over the world.",
        "",
        "Llamas belong to the camel family, which also includes camels, alpacas, vicuñas, and guanacos.",
        "Unlike camels, llamas do not have humps.",
        "They have thick, soft wool that helps keep them warm in the cool mountain climate.",
        "Their wool can be used to make blankets, rugs, ropes, and clothing.",
        "",
        "Llamas are herbivores, meaning they eat only plants.",
        "Their diet mainly consists of grasses, hay, shrubs, and other vegetation.",
        "They have a three-chambered stomach that helps them digest tough plant material efficiently.",
        "Adult llamas can grow to be about 5½ to 6 feet tall at the top of their heads and weigh between 280 and 450 pounds.",
        "",
        "One of the most famous things about llamas is that they sometimes spit.",
        "However, they usually spit at other llamas rather than people.",
        "Spitting is their way of showing annoyance, defending food, or settling disagreements.",
        "Most well-socialized llamas are calm and friendly toward humans.",
        "",
        "Llamas are highly social animals that enjoy living in groups.",
        "They communicate using soft humming sounds, ear positions, body language, and tail movements.",
        "Because they are alert and protective, some farmers even use llamas to guard sheep and other livestock from predators such as coyotes.",
        "",
        "🦙 Fun Llama Trivia",
        "",
        "Llamas have been domesticated for over 4,000 years.",
        "They are members of the camel family.",
        "A llama can comfortably carry about 25 to 30% of its body weight.",
        "Llamas usually spit at other llamas, not people.",
        "They communicate by making gentle humming sounds.",
        "Their wool is used to make clothing, blankets, rugs, and ropes.",
        "Some farmers use llamas as guard animals to help protect sheep from predators.",
        "A llama's ears are shaped like curved bananas! 🦙🍌 Their distinctive ears help them express emotions and communicate with other llamas through subtle movements.",
    ],
    questions: [
        "Where did llamas originally come from?",
        "What family of animals do llamas belong to?",
        "Why do llamas sometimes spit?",
        "True or False: Llamas eat meat.",
        "Name one way people use llamas today.",
    ],
    answers: [
        "The Andes Mountains of South America.",
        "The camel family.",
        "To show annoyance, defend food, or settle disagreements with other llamas.",
        "False. Llamas are herbivores and eat plants.",
        "Possible answers include carrying supplies, producing wool, guarding livestock, or living on farms."
    ] 
  },
  {
    id: "Sloths",
    title: "🦥 Sloths",
    topic: "Nature",
    category: "Animal",
    date: "Date: July 14, 2026",
    image: "/projects/daily-trivia/images/sonia-nadales-unsplash.jpg",
    youtube: "https://youtu.be/DpV4k3Edr-I?si=rWRhFLidesBrFfLR",
    information: [
        "🦥 Meet the Slow and Steady Sloth",
        "",
        "Sloths are gentle tree-dwelling mammals that live in the tropical rainforests of Central and South America. They are famous for moving slowly, but this isn't because they are lazy. Their slow movements help them conserve energy since their diet of leaves provides very little nutrition. By moving carefully and slowly, sloths can survive on much less food than many other mammals.",
        "There are six living species of sloths, divided into two groups: two-toed sloths and three-toed sloths. Despite their names, both types actually have three toes on their back feet. The difference is found in the number of claws on their front limbs. Sloths spend almost their entire lives hanging upside down from tree branches using their long, curved claws.",
        "",
        "Sloths are herbivores that mainly eat leaves, buds, shoots, and occasionally fruit. Their stomachs contain special bacteria that help break down tough leaves. Digestion is extremely slow and can take several weeks to finish a single meal. Because they digest food so slowly, sloths have one of the slowest metabolisms of any mammal.",
        "",
        "A sloth's thick fur is unique because it grows in the opposite direction from most mammals. Since sloths spend so much time hanging upside down, this helps rainwater run off their bodies. Their fur also becomes home to algae, giving many sloths a greenish tint that helps camouflage them among the leaves. Tiny insects, including certain moths and beetles, also live in their fur, creating a tiny ecosystem.",
        "",
        "Although sloths appear defenseless, they are excellent swimmers and can move through water much faster than they can move through trees. They can even hold their breath underwater for up to 40 minutes by slowing their heart rate. Their biggest natural predators include jaguars, harpy eagles, and large snakes.",
        "",
        "",
        "🦥 Fun Sloth Trivia",
        "",
        "Sloths sleep about 8 to 15 hours each day.",
        "",
        "They can turn their heads about 270 degrees to look around.",
        "",
        "Sloths are surprisingly strong swimmers.",
        "",
        "They can hold their breath for up to 40 minutes underwater.",
        "",
        "A sloth's fur often grows green algae, helping it blend into the forest.",
        "",
        "Digestion can take several weeks because of their slow metabolism.",
        "",
        "Sloths have existed for millions of years, and ancient relatives were once as large as elephants!",
        "",
        "",
        "🦥 Did You Know?",
        "Even though sloths seem sleepy all the time, they're perfectly adapted to life in the rainforest. Their slow lifestyle helps them avoid predators, conserve energy, and blend into the forest canopy. In a way, a sloth is like a living piece of the rainforest, carrying tiny plants and insects in its fur while quietly moving among the treetops."

    ],
    questions: [
        "Why do sloths move so slowly?",
        "What do sloths mainly eat?",
        "How does algae help a sloth?",
        "True or False: Sloths cannot swim.",
        "Name one predator of a sloth."
    ],
    answers: [
        "They move slowly to conserve energy because their leafy diet provides very little nutrition.",
        "They mainly eat leaves, along with buds, shoots, and sometimes fruit.",
        "The algae gives their fur a green color that helps camouflage them among the trees.",
        "False. Sloths are excellent swimmers and can move through water faster than they move through trees.",
        "Possible answers include jaguars, harpy eagles, or large snakes."
    ]
  },
  {
    id: "Raccoon",
    title: "Raccoon",
    topic: "Nature",
    category: "Animal",
    date: "Date: July, 9, 2026",
    image: "/projects/daily-trivia/images/raccoon.jpg",
    youtube: "https://www.youtube.com/embed/1lViKrWgTYk?si=0jGFxEidMZ6wxz9C",
    information: [
        "🦝 Meet the Curious Raccoon!",
        "",
        "Raccoons are one of North America's most recognizable wild animals, famous for the black `mask` around their eyes and their fluffy, ringed tails.These clever mammals can live in forests, wetlands, farms, and even busy cities, where they often search for food after the sun goes down. Raccoons are omnivores, which means they eat both plants and animals. Their menu can include fruits, nuts, insects, frogs, bird eggs, fish, and even leftovers they find in trash cans.Their front paws are incredibly sensitive and almost work like tiny hands, allowing them to open containers, turn doorknobs, and solve simple puzzles.",
        "",
        "Raccoons are known for their intelligence and excellent memory. Studies have shown they can remember solutions to problems for years, making them some of the smartest animals in the wild. Although many people believe raccoons always wash their food before eating, that isn't actually true. When food is near water, they often dip it because wetting their paws helps them gather more information about what they are holding. Most raccoons are active at night, and while they may look cute and cuddly, they are wild animals that should always be admired from a safe distance.",
        "",
        "🦝 Fun Raccoon Trivia.",
        "",
        "A raccoon's scientific name, Procyon lotor, means 'washing bear.'",
        "Raccoons have five fingers on each front paw, almost like a human hand",
        "Can climb trees headfirst by rotating their hind feet nearly 180 degrees.",
        "A raccoon's tail usually has 5 to 10 black rings.",
        "Baby raccoons are called kits or cubs.",
        "Raccoons are excellent swimmers and can also run up to 15 miles per hour.",
        "Despite their curious nature, raccoons are generally shy and prefer to avoid people whenever possible."
    ],
    questions: [
        "What is the black marking around a raccoon's eyes often called?",
        "What does it mean that raccoons are omnivores?",
        "Why are raccoons considered to be very intelligent?",
        "True or False: Raccoons always wash their food before they eat it.",
        "Name one interesting ability that helps raccoons survive in the wild."
    ],
    answers: [
        "A mask.",
        "They eat both plants and animals.",
        "They can solve problems and remember the solutions for years.",
        "False. They often dip food in water because wetting their paws helps them sense what they are holding, not because they are washing it.",
        "Possible Answers: They can climb trees headfirst, use their sensitive front paws like hands, swim well, run up to 15 mph, or remember how to solve problems."
    ]
  },
];

// Copy this shape when adding legacy worksheet topics so app.js can rely on a
// consistent set of fields without introducing special-case rendering.
//{
    //id: "",
    //title: "",
    //topic: "",
    //category: "",
    //date: "Date: ",
    //image: "/projects/daily-trivia/images/",
    //youtube: "",
    //information: [],
    //questions: [],
    //answers: []
  //},
